# NB: this file was automatically generated by Dynare
#     from ML.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(11, 15);
gp = zeros(11, 11, 15);
end
return (rp, gp)
end
