# NB: this file was automatically generated by Dynare
#     from ML.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    params[11]=((1/params[2]+params[3]-1)/params[1])^(1/(1-params[1]));
    params[14]=params[5]/params[11];
    params[12]=params[3]*params[14];
    params[13]=params[14]^params[1]*params[5]^(1-params[1]);
    params[15]=params[13]-params[12];
    params[10]=params[14]^params[1]*(1-params[1])*params[15]^(-params[4])*params[5]^(-params[1]);
    ys_[3]=params[14];
    ys_[4]=params[5];
    ys_[2]=params[15];
    ys_[1]=params[13];
    ys_[5]=params[12];
    ys_[8]=ys_[2]^(-params[4]);
    ys_[10]=params[1]*ys_[3]^(params[1]-1)*ys_[4]^(1-params[1]);
    ys_[11]=(1-params[1])*ys_[3]^params[1]*ys_[4]^(-params[1]);
    ys_[9]=ys_[8]*ys_[11];
    ys_[6]=0;
    ys_[7]=0;
    # Auxiliary equations
end
end
