# example showing how to do maximum likelihood estimation
# for data generated by CLRM with normality
# sample size

# explore size and power as the sample size grows

##
using Econometrics, Distributions
n = 100
# random true parameters
θ₀ = [1.0,-1.0,0.0,1.0]
b = θ₀[1:3]
sig = θ₀[4]
# generate random data
x = [ones(n,1) rand(n,2)]
e = sig*randn(n,1)
y = x*b + e

## do ML
obj = θ -> -mean(normal(θ, y, x))
θhat, logL, junk = fminunc(obj, θ₀)
logL = -logL

## restricted ML
R = [0 1 0 0]
r = -1.5
θhatr, logLr, junk = fmincon(obj, θ₀, R, r)
logLr = -logLr

## LR rest
LR = 2.0*n*(logL-logLr)

## results
println("the true parameters:")
display(θ₀)
println("\nthe ML estimates: ")
display(θhat)
println("\nthe restricted ML estimates: ")
display(θhatr)
println("\nthe LR test: ")
display(LR)
println("\np-value of the LR test: ")
display(1.0-cdf(Chisq(1),LR))
