# example showing how to do maximum likelihood estimation
# for data generated by CLRM with normality
# sample size
using Econometrics, Statistics
n = 10

# random true parameters
theta = [1.0,-1.0,0.0,1.0]
b = theta[1:3]
sig = theta[4]

# generate random data
x = [ones(n,1) rand(n,2)]
e = sig*randn(n,1)
y = x*b + e

# do ML: note minus sign, also, do "edit(normal)" to see what's done
obj = theta -> -mean(normal(theta, y, x))
thetahat, junk, junk = fminunc(obj, theta)

# results
println("the true parameters: ", theta)
println("the ML estimates: ", thetahat)
println("the OLS estimates: ", inv(x'*x)*x'*y)
